version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "24-wallet_balance_updated"
        Alias: "wallet_balance-alias"
        CurrentVersion: "1"
        TargetVersion: "2"
#Hooks:
#  - BeforeAllowTraffic: "LambdaFunctionToValidateBeforeTrafficShift"
#  - AfterAllowTraffic: "LambdaFunctionToValidateAfterTrafficShift"