version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing zip utility..."
      - apt-get update -y
      - apt-get install zip -y
      - apt-get install awscli -y  # Ensure awscli is installed

  pre_build:
    commands:
      - echo "Making sure the scripts directory exists..."
      - ls -la scripts/
      - echo "Making update-lambda-code.sh executable..."
      - chmod +x scripts/update-lambda-code.sh

  build:
    commands:
      - echo "Zipping index.js, appspec.yml, and scripts..."
      - zip -r deploy.zip index.js appspec.yml scripts/
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name 24-wallet_balance_updated --zip-file fileb://deploy.zip

artifacts:
  files:
    - deploy.zip
  discard-paths: yes
  base-directory: .
  name: deploy.zip
