version: 0.2

phases:
  install:
    commands:
      - echo "Installing zip utility..."
      - apt-get update -y
      - apt-get install zip -y

  build:
    commands:
      - echo "Making update_lambda_code.sh executable..."
      - chmod +x scripts/update_lambda_code.sh
      - echo "Zipping index.js, appspec.yml, and scripts..."
      - zip -r deploy.zip index.js appspec.yml scripts/

artifacts:
  files:
    - deploy.zip
  discard-paths: yes
  base-directory: .
  name: deploy.zip
