version: 0.2

phases:
  install:
    commands:
      - echo "Installing zip utility..."
      - apt-get install zip

  build:
    commands:
      - echo "Zipping index.js..."
      - zip deploy.zip index.js

artifacts:
  files:
    - deploy.zip
  discard-paths: yes